# Generated by Django 5.1.2 on 2024-11-01 11:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flowsheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('preview_url', models.URLField()),
                ('last_edited', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Auxilliary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('image_url', models.URLField()),
                ('image_width', models.IntegerField(default=60)),
                ('image_height', models.IntegerField(default=60)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('ORE', 'ore'), ('Storage Facility', [('STOCKPILE', 'stockpile'), ('BINS', 'bins')]), ('TAILING FACILITY', 'tailing facility'), ('OTHERS', 'others')], default='ORE', max_length=40)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='misc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Auxilliaries',
            },
        ),
        migrations.CreateModel(
            name='Concentrator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('image_url', models.URLField()),
                ('image_width', models.IntegerField(default=60)),
                ('image_height', models.IntegerField(default=60)),
                ('description', models.TextField(blank=True, null=True)),
                ('valuable_recoverable', models.DecimalField(decimal_places=1, default=20.0, max_digits=4)),
                ('gangue_recoverable', models.DecimalField(decimal_places=1, default=20.0, max_digits=4)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concentrators', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Crusher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('image_url', models.URLField()),
                ('image_width', models.IntegerField(default=60)),
                ('image_height', models.IntegerField(default=60)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crushers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FlowsheetObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('oid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('label', models.CharField(max_length=64)),
                ('x_coordinate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('y_coordinate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('scale', models.DecimalField(decimal_places=2, max_digits=5)),
                ('font_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('properties', models.JSONField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('flowsheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flowsheet_objects', to='flowsheet_app.flowsheet')),
            ],
        ),
        migrations.CreateModel(
            name='Grinder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('image_url', models.URLField()),
                ('image_width', models.IntegerField(default=60)),
                ('image_height', models.IntegerField(default=60)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grinders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='flowsheet',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flowsheets', to='flowsheet_app.project'),
        ),
        migrations.CreateModel(
            name='Screener',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('image_url', models.URLField()),
                ('image_width', models.IntegerField(default=60)),
                ('image_height', models.IntegerField(default=60)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='screeners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
