# Generated by Django 5.0.6 on 2024-07-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowsheet_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectobject',
            name='label',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
