# Generated by Django 5.0.6 on 2024-10-11 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowsheet_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auxilliary',
            name='image_height',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='auxilliary',
            name='image_width',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='concentrator',
            name='image_height',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='concentrator',
            name='image_width',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='crusher',
            name='image_height',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='crusher',
            name='image_width',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='grinder',
            name='image_height',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='grinder',
            name='image_width',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='screener',
            name='image_height',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='screener',
            name='image_width',
            field=models.IntegerField(default=60),
        ),
    ]
