# Generated by Django 5.0.6 on 2024-07-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowsheet_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectobject',
            name='temporary_object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
