# Generated by Django 5.1.2 on 2024-11-08 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowsheet_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowsheetobject',
            name='flowsheet',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='flowsheet_objects', to='flowsheet_app.flowsheet'),
        ),
    ]
