# Generated by Django 5.0.6 on 2024-10-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowsheet_app', '0002_auxilliary_image_height_auxilliary_image_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concentrator',
            name='gangue_recoverable',
            field=models.DecimalField(decimal_places=1, default=20.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='concentrator',
            name='valuable_recoverable',
            field=models.DecimalField(decimal_places=1, default=20.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='auxilliary',
            name='type',
            field=models.CharField(choices=[('ORE', 'ore'), ('Storage Facility', [('STOCKPILE', 'stockpile'), ('BINS', 'bins')]), ('TAILING FACILITY', 'tailing facility'), ('OTHERS', 'others')], default='ORE', max_length=40),
        ),
    ]
