# Generated by Django 5.0.6 on 2024-07-25 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowsheet_app', '0002_projectobject_temporary_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectobject',
            name='object_id',
        ),
    ]
