# Generated by Django 5.0.6 on 2024-07-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowsheet_app', '0003_remove_shape_image_alter_auxilliary_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shape',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
