# Generated by Django 5.0.6 on 2024-07-25 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowsheet_app', '0003_remove_projectobject_object_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectobject',
            old_name='temporary_object_id',
            new_name='object_id',
        ),
    ]
