# Generated by Django 5.1.2 on 2025-01-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowsheet_app', '0003_flowsheet_starred_project_last_edited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowsheet',
            name='preview_url',
            field=models.URLField(default='https://res.cloudinary.com/dpykexpss/image/upload/v1737482485/grid_je7dz4.png'),
        ),
    ]
