# Generated by Django 5.0.6 on 2024-06-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowsheet_app', '0003_concentrator_crusher_delete_concentrators_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miscellaneous',
            options={'verbose_name_plural': 'Miscellaneous'},
        ),
        migrations.AddField(
            model_name='crusher',
            name='gape',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='crusher',
            name='set',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='grinder',
            name='gape',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='grinder',
            name='set',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='miscellaneous',
            name='type',
            field=models.CharField(choices=[('ORE', 'ore'), ('Facility', [('STOCKPILE', 'stockpile'), ('BINS', 'bins')])], default='ORE', max_length=40),
        ),
    ]
