# Generated by Django 5.1.2 on 2025-03-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowsheet_app', '0004_alter_flowsheet_preview_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowsheet',
            name='background_preview_url',
            field=models.URLField(default='https://res.cloudinary.com/dpykexpss/image/upload/v1737482485/grid_je7dz4.png'),
        ),
        migrations.AlterField(
            model_name='flowsheet',
            name='preview_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
