# Generated by Django 5.0.6 on 2024-07-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowsheet_app', '0004_rename_temporary_object_id_projectobject_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectobject',
            name='x_coordinate',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='projectobject',
            name='y_coordinate',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
    ]
