# Generated by Django 5.0.6 on 2024-06-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowsheet_app', '0005_rename_user_project_creator_remove_concentrator_oid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concentrator',
            name='dilution_gain',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='concentrator',
            name='recovery_rate',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='projectobject',
            name='font_size',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='projectobject',
            name='scale',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
