# Generated by Django 5.1.2 on 2025-05-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowsheet_app', '0005_flowsheet_background_preview_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowsheet',
            name='save_frequence_type',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('AUTO', 'Auto')], default='MANUAL', max_length=10),
        ),
        migrations.AddField(
            model_name='flowsheet',
            name='save_frequency',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
