# Generated by Django 5.0.6 on 2024-07-30 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowsheet_app', '0005_alter_projectobject_x_coordinate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concentrator',
            name='dilution_gain',
        ),
        migrations.RemoveField(
            model_name='concentrator',
            name='recovery_rate',
        ),
        migrations.RemoveField(
            model_name='crusher',
            name='gape',
        ),
        migrations.RemoveField(
            model_name='crusher',
            name='set',
        ),
        migrations.RemoveField(
            model_name='crusher',
            name='type',
        ),
        migrations.RemoveField(
            model_name='grinder',
            name='gape',
        ),
    ]
