# Generated by Django 5.0.6 on 2024-06-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowsheet_app', '0006_alter_concentrator_dilution_gain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectobject',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
