# Generated by Django 5.1.2 on 2025-05-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowsheet_app', '0006_flowsheet_save_frequence_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auxilliary',
            name='type',
            field=models.CharField(choices=[('ORE', 'ore'), ('STORAGE FACILITY', [('STOCKPILE', 'stockpile'), ('BINS', 'bins')]), ('TAILING FACILITY', 'tailing facility'), ('OTHERS', 'others')], default='ORE', max_length=40),
        ),
    ]
