# Generated by Django 5.0.6 on 2024-07-30 15:17

import cloudinary.models
import django.utils.timezone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowsheet_app', '0006_remove_concentrator_dilution_gain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screener',
            name='test',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255, verbose_name='test'),
            preserve_default=False,
        ),
    ]
