# Generated by Django 5.1.2 on 2025-05-02 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowsheet_app', '0007_alter_auxilliary_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flowsheet',
            old_name='save_frequence_type',
            new_name='save_frequency_type',
        ),
    ]
