# Generated by Django 5.1.2 on 2025-08-17 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowsheet_app', '0008_rename_save_frequence_type_flowsheet_save_frequency_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('screenshots', models.JSONField(default=[])),
            ],
        ),
    ]
