# Generated by Django 5.1.2 on 2025-08-17 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowsheet_app', '0009_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='screenshots',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
