# Generated by Django 5.1.2 on 2025-11-15 13:42

# This file was generated to fix the error 
# django.db.utils.ProgrammingError: cannot cast type numeric to jsonb
# LINE 1: ...object" ALTER COLUMN "scale" TYPE jsonb USING "scale"::jsonb

# first running python manage.py makemigrations --empty flowsheet_app --name convert_scale_to_jsonb to create a migration file

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowsheet_app', '0010_alter_feedback_screenshots'),
    ]

    operations = [
         # 1. Add a temporary JSONB column
        migrations.RunSQL(
            'ALTER TABLE "flowsheet_app_flowsheetobject" ADD COLUMN "scale_temp" jsonb;'
        ),
        # 2. Copy data from numeric column to JSONB
        migrations.RunSQL(
            'UPDATE "flowsheet_app_flowsheetobject" SET "scale_temp" = to_jsonb("scale");'
        ),
        # 3. Drop old numeric column
        migrations.RunSQL(
            'ALTER TABLE "flowsheet_app_flowsheetobject" DROP COLUMN "scale";'
        ),
        # 4. Rename temp column to original name
        migrations.RunSQL(
            'ALTER TABLE "flowsheet_app_flowsheetobject" RENAME COLUMN "scale_temp" TO "scale";'
        ),
    ]
