# Generated by Django 5.1.2 on 2025-11-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flowsheet_app", "0010_alter_feedback_screenshots"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flowsheetobject",
            name="scale",
            field=models.JSONField(default={"x": 1.25, "y": 1.25}),
        ),
    ]
