# Generated by Django 5.1.2 on 2025-11-05 12:57

import flowsheet_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flowsheet_app", "0011_alter_flowsheetobject_scale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flowsheetobject",
            name="scale",
            field=models.JSONField(default=flowsheet_app.models.default_scale),
        ),
    ]
