# Generated by Django 5.1.2 on 2025-05-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_oauth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
